/**
 * «Copyright 2025 Roberto Reinosa Fernández»
 * 
 * This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

package com.RRF.OrfViralScan;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author Roberto Reinosa Fernández
 */

public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    
    public static String entrada;
    public static String salida;
    
    public Interfaz() {
        
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/com/RRF/OrfViralScan/Logo/Logo OrfViralScan.png")).getImage());

        setLocationRelativeTo(null);      
   
        setTitle("OrfViralScan 3.0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogEntrada = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        DialogSalida = new javax.swing.JDialog();
        jFileChooser2 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();

        DialogEntrada.setSize(new java.awt.Dimension(1000, 500));

        jFileChooser1.setMaximumSize(new java.awt.Dimension(1000, 500));
        jFileChooser1.setMinimumSize(new java.awt.Dimension(1000, 500));
        jFileChooser1.setPreferredSize(new java.awt.Dimension(1000, 500));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        DialogEntrada.getContentPane().add(jFileChooser1, java.awt.BorderLayout.CENTER);

        DialogSalida.setSize(new java.awt.Dimension(1000, 500));

        jFileChooser2.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        jFileChooser2.setMaximumSize(new java.awt.Dimension(1000, 500));
        jFileChooser2.setMinimumSize(new java.awt.Dimension(1000, 500));
        jFileChooser2.setPreferredSize(new java.awt.Dimension(1000, 500));
        jFileChooser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser2ActionPerformed(evt);
            }
        });
        DialogSalida.getContentPane().add(jFileChooser2, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 520));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 520));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 520));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 123, 255));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Input");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 30, 120, 35);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Input File:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 20, 73, 17);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(136, 136, 136));
        jLabel2.setText("No file selected");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 50, 180, 16);

        jComboBox1.setBackground(new java.awt.Color(254, 254, 254));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "Input Strand", "Antiparallel Strand", "Both" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(210, 200, 160, 34);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Calculation type:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 90, 150, 17);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Length:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 170, 160, 17);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(110, 200, 70, 24);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Range:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 280, 160, 17);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(30, 310, 160, 24);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(210, 310, 160, 24);

        jButton3.setBackground(new java.awt.Color(40, 167, 69));
        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(254, 254, 254));
        jButton3.setText("Calculate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 430, 160, 35);

        jButton2.setBackground(new java.awt.Color(220, 53, 69));
        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(254, 254, 254));
        jButton2.setText("Cancel");
        jButton2.setMaximumSize(new java.awt.Dimension(67, 28));
        jButton2.setMinimumSize(new java.awt.Dimension(67, 28));
        jButton2.setPreferredSize(new java.awt.Dimension(67, 28));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 430, 160, 35);

        jCheckBox1.setFont(new java.awt.Font("Ubuntu Sans", 1, 15)); // NOI18N
        jCheckBox1.setText("Select Range");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(30, 240, 200, 24);

        jButton4.setBackground(new java.awt.Color(0, 123, 255));
        jButton4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(254, 254, 254));
        jButton4.setText("Output");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(30, 370, 120, 35);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(136, 136, 136));
        jLabel4.setText("No file selected");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 390, 180, 16);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Output file:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 360, 85, 17);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("Orientation:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 170, 160, 17);

        jComboBox3.setBackground(new java.awt.Color(254, 254, 254));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ...", "ORF Search", "Track Specific ORF", "Preprocess File", "Divide Into Fragments" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(30, 120, 340, 34);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(30, 200, 70, 24);

        jCheckBox2.setFont(new java.awt.Font("Ubuntu Sans", 1, 15)); // NOI18N
        jCheckBox2.setText("aa");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(300, 250, 102, 24);

        jCheckBox3.setFont(new java.awt.Font("Ubuntu Sans", 1, 15)); // NOI18N
        jCheckBox3.setText("nt");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(240, 250, 42, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DialogEntrada.setLocationRelativeTo(null);
        DialogEntrada.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        jButton3.setEnabled(false);
        
        if(jComboBox3.getSelectedIndex() == 1){
        
            int lecturaCadenas = jComboBox1.getSelectedIndex();
                      
            Hilo_Busqueda_ORFs busquedaORFs = new Hilo_Busqueda_ORFs(entrada, salida, lecturaCadenas);

            
            
        }else if(jComboBox3.getSelectedIndex() == 2){
            
            int selectorTipoSecuencia = -1;
            
            if(jCheckBox3.isSelected()){
                
                selectorTipoSecuencia = 0;
                
            }
            
            if(jCheckBox2.isSelected()){
                
                selectorTipoSecuencia = 1;
                
            }
            
            int regionInferior;
            int regionSuperior;
            
            if(!jCheckBox1.isSelected()){
                
                regionInferior = -1;
                regionSuperior = -1;
                
            }else{
                
                try{
                
                    regionInferior = Integer.parseInt(jTextField4.getText())-1;
                    regionSuperior = Integer.parseInt(jTextField5.getText());
                
                }catch(Exception e){
                
                    regionInferior = -1;
                    regionSuperior = -1;
                    
                }
                
            }
            
            int orientacion = jComboBox1.getSelectedIndex(); 
            
            int longitudMinima = Integer.parseInt(jTextField2.getText());
            int longitudMaxima = Integer.parseInt(jTextField1.getText());
            
            if((jCheckBox1.isSelected() && !jTextField4.getText().equals("") && !jTextField5.getText().equals("")) || !jCheckBox1.isSelected()){
                
                if(!jCheckBox2.isSelected() && !jCheckBox3.isSelected()){
                
                    jButton3.setEnabled(true);
                    
                }else{
                    
                    Hilo_Rastreador_ORF rastreadorORF = new Hilo_Rastreador_ORF(entrada, salida, longitudMinima, longitudMaxima, regionInferior, regionSuperior, orientacion, selectorTipoSecuencia);

                }
                
            }else{
                
                jButton3.setEnabled(true);
                
            }
            
        }else if(jComboBox3.getSelectedIndex() == 3){
            
            Hilo_Preprocesar_Archivo preprocesarArchivo = new Hilo_Preprocesar_Archivo(entrada, salida);
            
        }else if(jComboBox3.getSelectedIndex() == 4){
            
            Hilo_Dividir dividirSecuencia = new Hilo_Dividir(entrada, salida);
            
        }else{
            
            jButton3.setEnabled(true);
            
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Cancelar_Hilos.cargarCancelarHilos();
        jButton3.setEnabled(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        DialogSalida.setLocationRelativeTo(null);
        DialogSalida.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        
        if(jCheckBox1.isSelected()){
            
            jTextField4.setEnabled(true);
            jTextField5.setEnabled(true);
            
        }else{
            
            jTextField4.setEnabled(false);
            jTextField5.setEnabled(false);
            
        }
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed

        String command = evt.getActionCommand();

        if(command.equals(JFileChooser.APPROVE_SELECTION)){

            String ruta = String.valueOf(jFileChooser1.getSelectedFile()) + "/";

            entrada = ruta;

            String rutaSalida = "... ";

            if(ruta.length() <= 25){

                rutaSalida = ruta;

            }else{

                for(int i = ruta.length()- 25; i < ruta.length(); i++){

                    rutaSalida += ruta.toCharArray()[i];

                }

            }

            jLabel2.setText(rutaSalida);

            DialogEntrada.dispose();

        }else if(command.equals(JFileChooser.CANCEL_SELECTION)){

            DialogEntrada.dispose();

        }

    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jFileChooser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser2ActionPerformed
        
        String command = evt.getActionCommand();

        if(command.equals(JFileChooser.APPROVE_SELECTION)){

            String ruta = String.valueOf(jFileChooser2.getSelectedFile()) + "/";

            salida = ruta;

            String rutaSalida = "... ";

            if(ruta.length() <= 25){

                rutaSalida = ruta;

            }else{

                for(int i = ruta.length()- 25; i < ruta.length(); i++){

                    rutaSalida += ruta.toCharArray()[i];

                }

            }

            jLabel4.setText(rutaSalida);

            DialogSalida.dispose();

        }else if(command.equals(JFileChooser.CANCEL_SELECTION)){

            DialogSalida.dispose();

        }
        
    }//GEN-LAST:event_jFileChooser2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        
        switch (jComboBox3.getSelectedIndex()) {
            
            case 0:
                
                jComboBox1.setEnabled(true);
                
                jTextField2.setEnabled(true);
                jTextField1.setEnabled(true);
                jTextField4.setEnabled(true);
                jTextField5.setEnabled(true);
                
                jCheckBox1.setEnabled(true);
                jCheckBox3.setEnabled(true);
                jCheckBox2.setEnabled(true);
                
                break;
                
            case 1:
                
                jComboBox1.setEnabled(true);
                
                jTextField2.setEnabled(false);
                jTextField1.setEnabled(false);
                jTextField4.setEnabled(false);
                jTextField5.setEnabled(false);
                
                jCheckBox1.setEnabled(false);
                jCheckBox3.setEnabled(false);
                jCheckBox2.setEnabled(false);
                
                break;
                
            case 2:
                
                jComboBox1.setEnabled(true);
                
                jTextField2.setEnabled(true);
                jTextField1.setEnabled(true);
                
                jCheckBox1.setEnabled(true);
                
                if(jCheckBox1.isSelected()){
                    
                    jTextField4.setEnabled(true);
                    jTextField5.setEnabled(true);
                    
                }else{
                    
                    jTextField4.setEnabled(false);
                    jTextField5.setEnabled(false);
                    
                }
                
                jCheckBox3.setEnabled(true);
                jCheckBox2.setEnabled(true);
                
                break;
                
            case 3:
            case 4:
                
                jComboBox1.setEnabled(false);
                
                jTextField2.setEnabled(false);
                jTextField1.setEnabled(false);
                jTextField4.setEnabled(false);
                jTextField5.setEnabled(false);
                
                jCheckBox1.setEnabled(false);
                jCheckBox3.setEnabled(false);
                jCheckBox2.setEnabled(false);
                
                break;
                
            default:
                
                break;
                
        }
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        
        if(jCheckBox3.isSelected()){
            
            jCheckBox2.setSelected(false);
            
        }
        
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        
        if(jCheckBox2.isSelected()){
            
            jCheckBox3.setSelected(false);
            
        }
        
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        
        UIManager.setLookAndFeel(new NimbusLookAndFeel());
        
        UIManager.put("TextField[Focused].borderPainter", new Color(255, 255, 255));
        UIManager.put("nimbusSelectionBackground", new Color(255, 255, 255));
                        
        UIManager.put("controlShadow", new Color(255, 255, 255));
        UIManager.put("control",new Color(255, 255, 255));
        UIManager.put("nimbusSelectionBackground", new Color(233, 84, 32));
        UIManager.put("nimbusFocus", new Color(230, 230, 230));
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogEntrada;
    private javax.swing.JDialog DialogSalida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public static javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
